services:
  dalec-docker-extension:
    image: ${DESKTOP_PLUGIN_IMAGE}
    volumes:
      # Mount Docker socket to run docker commands
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - PORT=8080
